### ISSUE TITLE
Qos 

### ISSUE THREAD

**Issue by ekhoury2000** [jadiaz/MikroTik#1]
Hi @jadiaz 

I am looking for a configuration that enables me to configure my 10 MB WAN connection into multiple users, while prioritizing games on other traffic types like web browsing ...

can your code help me? or should i look into something more recent?

i tried using simple queues and pcq but never was able to get the results i hope or without having spikes while in games.

Thanks in advance

**Comment by jadiaz** [comment]
This script is generic and will not prioritize traffic types. I recommend asking around in the Mikrotik forums.

**Comment by ekhoury2000** [comment]
ok Thanks for the help
